### ISSUE TITLE
Outdated onboarding guide.

### ISSUE THREAD

**Issue by johannbg** [packit/packit.dev#287]
All the branches in Fedora have been politically corrected to main from master and the onboarding guide does not reflect that [1] ( which we hit with our last release ) and now we are bitten by https://github.com/dracutdevs/dracut/issues/1524 so it would be nice if the on boarding guide gets a spoon feeding section added on what needs to be done on the "fedora" side of things to get things working properly there. 

1. https://packit.dev/docs/guide/

**Comment by jpopelka** [comment]
Sorry for the issue, I checked the logs, but don't know what's the culprit.
I created packit/packit-service#1107 and moved this one to the packit.dev repo to fix the outdated guide.

**Comment by lachmanfrantisek** [comment]
Isn't it already solved? I can see only one occurrence of `master` in the linked page and that is the name of our Copr repo which we haven't renamed because of the backwards compatibility. (But it has been built from the `main` branch for some time already.)

**Comment by mfocko** [comment]
I see references here:
- [ ] [`propose-downstream`, might be caused by `git` defaults](https://github.com/packit/packit.dev/blob/327b00af346186a35f37fee4a163e8896e2acb04/content/docs/CLI/propose-downstream.md#L55)
- [ ] [how to source-git, might be the same reason](https://github.com/packit/packit.dev/blob/327b00af346186a35f37fee4a163e8896e2acb04/content/docs/source-git/how-to-source-git.md#L78-L79)
- [ ] [sync from downstream, this one is updated after the dist-git was moved to `main`/`rawhide`](https://github.com/packit/packit.dev/blob/327b00af346186a35f37fee4a163e8896e2acb04/content/docs/CLI/sync-from-downstream.md#L46-L48)
- [ ] then there's also one reference regarding testing farm (default git ref for fetching tests)
- [X] older posts with regular updates, doesn't make sense to update retrospectively imo
