### ISSUE TITLE
Create a blog-post about VM image builds

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/packit.dev#788]
* [ ] Describe all the steps needed to be covered (when done manually) so we can compare that with Packit's automation.
* [ ] Describe the usage via Packit (with screenshots) for people that do not know Packit
* [ ] Publish to developer portal

**Comment by TomasTomecek** [comment]
I'm unassigning myself as I won't have bandwidth to do this, sorry :/

Since this is meant to be used by customers with development subs, we should register as such on console.redhat.com

I propose this structure for the blog post.

Title: Customize AWS cloud images with Image Builder and Packit

1. Packit intro
  * install the app, get approved
  * set up RPM builds and VM image build 
  * verify it works, show how to install those RPMs
3. console.redhat.com
  * create a new account using the developer sub 
  * pair with AWS
5. Choose project: ideally something that can be demonstrated in the terminal, our hello-world is a good candidate
6. Create a PR with a change (i.e. change terminal color of "world" output)
7. kick off vm_image_build
  * inform them the image can't be accessed in their console.rh.c
  * it's shared with AWS
9. go to AWS, create EC2 instance, verify

**Comment by majamassarini** [comment]
Blogpost draft: https://github.com/packit/packit.dev/pull/816

The **Custom respositories** feature has been **temporarily disabled**, waiting for it to be back for finishing the post.
